add new test job for debian
Signed-off-by: amantova <amantova@qti.qualcomm.com>

diff --git a/.github/workflows/build-ci.yml b/.github/workflows/build-ci.yml
--- a/.github/workflows/build-ci.yml
+++ b/.github/workflows/build-ci.yml
@@ -115,5 +115,21 @@ jobs:
           docker run --rm --privileged \
           --security-opt seccomp=unconfined \
           --security-opt apparmor=unconfined \
-          -e HOST_UID=$(id -u) -e HOST_GID=$(id -g) \
+          mini-sandbox-suse:"${TAG}"
+
+      - name: Build Debian container
+        run: |
+          test -d dist || (echo "dist/ missing" && exit 1)
+
+          docker build \
+            -f mini_sandbox/utils/mini_sandbox_docker/Dockerfile.debian \
+            --build-arg V=dist \
+            -t mini-sandbox-suse:"${TAG}" \
+            .
+
+      - name: Run SUSE container
+        run: | 
+          docker run --rm --privileged \
+          --security-opt seccomp=unconfined \
+          --security-opt apparmor=unconfined \
           mini-sandbox-suse:"${TAG}"
